wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690656741.830423
    t:
      1:
      - 55
      - 86
      - 95
      2:
      - 55
      - 86
      - 92
      - 95
      3:
      - 23
      4: 3.11.4
      5: 0.15.7
      8:
      - 4
      - 5
      - 9
